#define CONFIG_USB_HOLYMAP_MULTITOUCH_VENDOR_ID  	0x040b
#define CONFIG_USB_HOLYMAP_MULTITOUCH_PRODUCT_ID	0x2230

#define TOUCHSCREEN_MINX (0x0000)
#define TOUCHSCREEN_MINY (0x0000)
#define TOUCHSCREEN_MAXX (0x4BFF)//(0x45FF)//
#define TOUCHSCREEN_MAXY (0x2BFF)//(0x2BFF)//


